# This workflow will push a PHP application ftp

name: Build and deploy PHP app to FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PHP_VERSION: '8.x'                  # set this to the PHP version to use

jobs:
  web-deploy:
      name: 🎉 Deploy
      runs-on: ubuntu-latest
      steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      
      # - name: Create env file
      #   run: |
      #       touch .env
      #       echo APP_NAME=MyAppName >> .env
      #       echo APP_ENV=production >> .env
      #       echo APP_DEBUG=false >> .env
      #       echo LOG_CHANNEL=daily >> .env
      #       echo DB_DATABASE=${{ secrets.DEV_DB_DATABASE }} >> .env
      #       echo DB_USERNAME=${{ secrets.DEV_DB_USERNAME }} >> .env
      #       echo DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }} >> .env
      #       echo "!.env" > .git-ftp-include

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.SERVIDORCETE }}
          username: ${{ secrets.USUARIOTE }}
          password: ${{ secrets.CONTRASENIA }}
