# This workflow will push a PHP application ftp

name: Build and deploy PHP app to FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PHP_VERSION: '8.x'                  # set this to the PHP version to use

jobs:
  web-deploy:
      name: 🎉 Deploy
      runs-on: ubuntu-latest
      steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.SERVIDORCETE }}
          username: ${{ secrets.USUARIOTE }}
          password: ${{ secrets.CONTRASENIA }}
