name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Archivos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.SERVIDORCETE }}
        user: ${{ secrets.USUARIOTE }}
        password: ${{ secrets.CONTRASENIA }}
        localDir: "."
        remoteDir: "."
  
  build:
    name: El puto vendor
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Instalando Vendor
      uses: php-actions/composer@v6
      
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.SERVIDORCETE }}
        user: ${{ secrets.USUARIOTE }}
        password: ${{ secrets.CONTRASENIA }}
        localDir: "vendor"
        remoteDir: "vendor"